### ISSUE TITLE
Testing with kaiosrt simulator not working

### ISSUE THREAD

**Issue by Phidelux** [kaiostech/sample-react#1]
Hi,

I am running Linux and as I had problems testing my application with the [kaiosrt](https://developer.kaiostech.com/getting-started/env-setup/simulator) simulator, I tried to test the react example with it. However, there are several problems. First of all, the WebIDE based kaiosrt, searches for the [webapp manifest](https://developers.google.com/web/fundamentals/web-app-manifest/) in the project's root directory, whereas the sample project placed it in the public/ directory. Furthermore starting the app after running `npm install` results in the error 

> Operation timed out: Installing and running app ...

and the display of an empty loading app afterwards. Finally there is a warning caused by a missing 128px app icon.

I was able to test the application with Chromium, but had problems using other keys than the arrow keys, return and normal text input (could not delete todos). How can I test the example and other react applications using the kaiosrt simulator or the chromium debugger.

Thanks and best regards
Andreas

**Comment by johnatandias** [comment]
Hi @Phidelux,

Thank you for your interest in our platform.

You must first execute the command `npm run build` or `yarn build`, after the script finishes, you must [follow the steps outlined in the developer portal](https://developer.kaiostech.com/getting-started/build-your-first-app/test-your-apps#simulator), when you get to the upload folder, select the build folder.
